[package]
name = "picoscope-egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "*"
eframe = "*"
epi = "*"
pico-sdk = { path = "subs/pico-sdk/sdk" }
crossbeam-channel = "*"
rustfft = "*"
